//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class Location
    {
        public Location()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int LocationId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Concierge { get; set; }
        public Nullable<bool> PromoterOnly { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
