//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class Status
    {
        public Status()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int StatusId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
