//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public class Ticket
    {
        public int TicketId { get; set; }
        public int VenueId { get; set; }
        public int CustomerId { get; set; }
        [NotMapped]
        public int VenueTypeId { get; set; }
        public System.DateTime TicketDate { get; set; }
        [NotMapped]
        public DateTime TicketTime { get; set; }
        public Nullable<int> MaleCount { get; set; }
        public Nullable<int> FemaleCount { get; set; }
        public Nullable<int> FinalMaleCount { get; set; }
        public Nullable<int> FinalFemaleCount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PromoterId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string OtherLocation { get; set; }
        public Nullable<bool> GuestList { get; set; }
        public Nullable<bool> BottleService { get; set; }
        public Nullable<bool> ContactPromoter { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Location Location { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
        public virtual User Promoter { get; set; }          
        public virtual Venue Venue { get; set; }
    }
}
