//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class VenueType
    {
        public VenueType()
        {
            this.Venues = new HashSet<Venue>();
        }
    
        public int VenueTypeId { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Venue> Venues { get; set; }
    }
}
